### ISSUE TITLE
Docker Compose Help

### ISSUE THREAD

**Issue by cloudbr34k84** [NSPManager/NSPanelManager#154]
Does anyone have a docker-compose file i could use? Im ok with these, but i can't get this to work when i run it using Powershell it says it doesnt like property url or  homeassistant_api..

```
version: "3.9"
networks:
  traefik:
    external: true
services:
  nspanelmanager:
    image: docker.io/nspanelmanager/nspanelmanager-amd64
    container_name: nspanelmanager
    network_mode: host
    url: "https://nspanelmanager.com"
    webui: http://xxxxxxxxxxxx:8000/
    panel_icon: mdi:fit-to-screen
    ports:
     - 8000:8000
     - 8001:8001
    environment:
      IS_HOME_ASSISTANT_ADDON: "true"
    init: false
    homeassistant_api: true
    restart: unless-stopped
    labels:      
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.XXXX.tls=true"
      - "traefik.http.routers.XXXX.tls.certresolver=dnsresolver"
      - "traefik.http.routers.XXXX.rule=Host(`XXXX.cloudbr34k.xyz`)"
      - "traefik.http.routers.XXXX.entrypoints=https"
      - "traefik.http.routers.XXXX.service=svcXXXX"
      - "traefik.http.services.svcXXXX.loadbalancer.server.port=XXXX"
      - "traefik.http.routers.XXXX.middlewares=auth@file"
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - default
     ```
